// Code generated by go generate; DO NOT EDIT.
package modules

import (
	_ "github.com/hikari-work/userbot/modules/admins"
	_ "github.com/hikari-work/userbot/modules/afk"
	_ "github.com/hikari-work/userbot/modules/antiflood"
	_ "github.com/hikari-work/userbot/modules/download"
	_ "github.com/hikari-work/userbot/modules/filter"
	_ "github.com/hikari-work/userbot/modules/json"
	_ "github.com/hikari-work/userbot/modules/lang"
	_ "github.com/hikari-work/userbot/modules/menu"
	_ "github.com/hikari-work/userbot/modules/ping"
	_ "github.com/hikari-work/userbot/modules/pmpermit"
	_ "github.com/hikari-work/userbot/modules/prefix"
	_ "github.com/hikari-work/userbot/modules/quote"
	_ "github.com/hikari-work/userbot/modules/spam"
	_ "github.com/hikari-work/userbot/modules/status"
	_ "github.com/hikari-work/userbot/modules/voicechat"
)
