services:
  redis:
    image: redis:7-alpine
    container_name: userbot_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass "${REDIS_PASS:-yourdefaultpassword}" --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - userbot_net

  userbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: userbot_app
    restart: always
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_URI=redis:6379
      - REDIS_PASS=${REDIS_PASS:-yourdefaultpassword}
      - GOCACHE=/go-cache
      - GOMODCACHE=/go-mod-cache
      - CGO_ENABLED=0
    volumes:
      - .:/app
      - go_cache:/go-cache
      - go_mod_cache:/go-mod-cache
    networks:
      - userbot_net

volumes:
  redis_data:
  go_cache:
  go_mod_cache:

networks:
  userbot_net:
    driver: bridge
