//go:build ignore

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	modulesDir := "modules"
	outputFile := filepath.Join(modulesDir, "imports.go")

	if _, err := os.Stat(modulesDir); os.IsNotExist(err) {
		err := os.MkdirAll(modulesDir, 0755)
		if err != nil {
			fmt.Printf("failed to create folder modules, try to check permission: %v\n", err)
			os.Exit(1)
		}
	}

	files, err := os.ReadDir(modulesDir)
	if err != nil {
		fmt.Printf("failed to read folder modules, try to check permission: %v\n", err)
		os.Exit(1)
	}

	var imports []string
	for _, f := range files {
		if f.IsDir() && f.Name() != "manager" {
			pkgPath := fmt.Sprintf("\t_ \"github.com/hikari-work/userbot/modules/%s\"", f.Name())
			imports = append(imports, pkgPath)
		}
	}

	var importSection string
	if len(imports) > 0 {
		importSection = fmt.Sprintf("import (\n%s\n)", strings.Join(imports, "\n"))
	} else {
		importSection = "// No modules registered yet"
	}

	content := fmt.Sprintf(`// Code generated by go generate; DO NOT EDIT.
package modules

%s
`, importSection)

	err = os.WriteFile(outputFile, []byte(content), 0644)
	if err != nil {
		fmt.Printf("Failed to write imports.go: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("modules/imports.go has been generated!")
}
